blueprint:
  name: Aqara Wireless Button WXKG11LM (Zigbee MQTT Trigger)
  description: "Triggers actions based on Zigbee2MQTT button presses"
  domain: automation
  input:
    helper_last_controller_event:
      name: Helper Last Controller Event
      selector:
        entity:
          domain: input_text
    entity_id:
      name: Entity to Set
      selector:
        entity: {}

trigger:
  - platform: mqtt
    topic: zigbee2mqtt/<device name>

variables:
  command: "{{ trigger.payload_json.action | default('') }}"
  prev_command: "{{ states(input.helper_last_controller_event) }}"

condition:
  - condition: template
    value_template: "{{ command != '' }}"

action:
  - service: input_text.set_value
    data:
      entity_id: !input helper_last_controller_event
      value: "{{ command }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ command == 'single' }}"
        sequence: []
      - conditions:
          - condition: template
            value_template: "{{ command == 'hold' }}"
        sequence: []
      - conditions:
          - condition: template
            value_template: "{{ command == 'release' }}"
        sequence: []
      - conditions:
          - condition: template
            value_template: "{{ command == 'double' }}"
        sequence: []
      - conditions:
          - condition: template
            value_template: "{{ command == 'triple' }}"
        sequence: []
